[workspace]
members = [
    "src/asset",
    "src/base",
    "src/device",
    "src/gfx",
    "src/math",
    "src/prelude",
    "src/spirv",
    "src/unit",
    "src/window",
]

[profile.dev.package."*"]
opt-level = 3
