[package]
name = "cooper-spirv"
version = "0.1.0"
authors = ["Matthew McAllister <matthew.mcallister.0@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
derivative = "2.1.1"
fnv = "1.0.7"
rspirv = "0.6.0"
spirv_headers = "1.4.2"
