[package]
name = "cooper-main"
version = "0.1.0"
authors = ["Matthew McAllister <matthew.mcallister.0@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
derivative = "1.0"
derive_more = "0.14"
memoffset = "0.3"
graphics = { path = "../graphics", package = "cooper-graphics" }
window = { path = "../window", package = "cooper-window" }

[[bin]]
name = "cooper"
path = "src/main.rs"
