[package]
name = "cooper-math"
version = "0.1.0"
authors = ["Matthew McAllister <matthew.mcallister.0@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
base = { path = "../base", package = "cooper-base" }
approx = "0.3"
prelude = { path = "../prelude", package = "cooper-prelude" }
